name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npx tsc

      - name: Print valuables for debugging
        run: |
          echo "EC2_HOST is: ${{ vars.EC2_HOST }}"
          echo "EC2_USER is: ${{ vars.EC2_USER }}"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -avz --delete dist package*.json ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }}:/home/ubuntu/github_pages/choi-hyk.github.io.server/
          ssh ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }} "
            cd /home/ubuntu/github_pages/choi-hyk.github.io.server &&
            npm ci --omit=dev &&
            pm2 restart choi-hyk.github.io-api || pm2 start dist/app.js --name choi-hyk.github.io-api
          "
